### ISSUE TITLE
关于设置电表清零的设置

### ISSUE THREAD

**Issue by Carlos6668** [liwei19920307/ESP485#4]
你好，我想问一下，看到电表说明书中有关于电表清零的设置，在ESP HOME固件中是否可以增加一个按钮来对电表进行清零，我研究了好久实在是没看懂，不知道是否可以帮忙看下，谢谢

**Comment by liwei19920307** [comment]
这个之前测试过 不过esphome的

**Comment by liwei19920307** [comment]
> 你好，我想问一下，看到电表说明书中有关于电表清零的设置，在ESP HOME固件中是否可以增加一个按钮来对电表进行清零，我研究了好久实在是没看懂，不知道是否可以帮忙看下，谢谢

这个以前测试过 esphome不支持

**Comment by liwei19920307** [comment]
> 你好，我想问一下，看到电表说明书中有关于电表清零的设置，在ESP HOME固件中是否可以增加一个按钮来对电表进行清零，我研究了好久实在是没看懂，不知道是否可以帮忙看下，谢谢

esphome目前只支持4种[功能码](https://esphome.io/components/binary_sensor/modbus_controller)主要是读取

可以使用[这里](https://esphome.io/components/button/uart)的按钮（这个以前还不支持，之前只有switch组件支持发送报文，但有bug所以我没有放出来）

我尝试写了两个按钮，有空可以测试下，我没有多余设备测试

如何生成报文可以看下说明书和这篇[文章](https://www.luofenming.com/show.aspx?id=cc160da7e8874664883d1ad2788e7748)

主要是把设备地址，和CRC校验搞明白应该就没问题

```yml
button:
  - platform: uart
    name: ep_reset1
    data: [0x01, 0x06, 0x00, 0x02, 0x00, 0x01, 0x24, 0x61]
  - platform: uart
    name: ep_reset2
    data: [0x01, 0x10, 0x00, 0x02, 0x00, 0x01, 0x02, 0x00, 0x01, 0x62, 0x05]
```

**Comment by Carlos6668** [comment]
刚才测试了一下，貌似没有效果，电表没有清零。
![QQ截图20240130130724](https://github.com/liwei19920307/ESP485/assets/16048692/b669d34c-d94a-444a-98c1-6ef9559101a4)
![QQ截图20240130130546](https://github.com/liwei19920307/ESP485/assets/16048692/de41fe12-20ff-468a-b6ec-47c4ebb4b7e1)

**Comment by liwei19920307** [comment]
试试这个，最后的校验位我搞错了，群友测试可以的，有问题可以加群讨论

```
button:
  - platform: restart
    name: ${device_name}_reboot
  - platform: uart
    name: ${device_name}_ep_reset
    data: [0x01, 0x10, 0x00, 0x02, 0x00, 0x01, 0x02, 0x00, 0x01, 0x66, 0x72]
```

**Comment by 602293544** [comment]
```
button:
  - platform: template
    name: ${device_name}_1_clear
    on_press:
      - uart.write: [0x01, 0x10, 0x00, 0x02, 0x00, 0x01, 0x02, 0x00, 0x01, 0x66, 0x72]
```
